### ISSUE TITLE
textarea height is not adjusted accroding to it's content when reloading the page.

### ISSUE THREAD

**Issue by gangamweb** [evseevdev/ngx-textarea-autosize#10]
While typing the text in to textarea height is adjusting accroding to it's content.but after reloading the page  height of the textarea is setting to intial height.check  screenshot.
![whiletyping](https://user-images.githubusercontent.com/40229615/41977106-363c0ce0-7a3c-11e8-8202-e2b954be8c75.PNG)
![afterreloading](https://user-images.githubusercontent.com/40229615/41977125-3ea81ff4-7a3c-11e8-8b27-d8d77cfbc7ba.PNG)

This is the html mark up 
<textarea placeholder="Enter Explanation {{statement.id}}"  [(ngModel)]="statement.Expl" autosize></textarea>

**Comment by RenuDaffodilsw** [comment]
Hi @evseevdev have you fixed this bug ?
I am facing the same problem.

**Comment by HrideshDaffodil** [comment]
Hi @evseevdev,

I am facing the same issue. Have you fixed it?

**Comment by JoseXS** [comment]
Lo mismo por aqui, bug sin solucionar...

**Comment by martijnluyckx** [comment]
I am encountering the same issue.

**Comment by kombadzomba** [comment]
Me too after upgrade to Angular6 and `ngx-textarea-autosize` to `2.0.0`. Previous version was `1.1.1` and it was ok with ng5 but `1.1.1` does not work with ng6.

**Comment by nbunney** [comment]
Looks like still not fixed.  Any update @evseevdev.  Praying for you have the time to get this fixed sometime soon.  Thanks for a great directive.

**Comment by MrCroft** [comment]
I'm also facing this issue when I change the content programmatically (patchValue on the form control).
I suppose it's more or less the same issue, a title like "textarea height is not adjusted [...] **when content comes from any other source, other than direct user input**" would probably cover more ground.
In addition to resizing in ngOnInit() (based on the content), it would have been great if the directive exposed the resize() method, so we could also call it ourselves when needed. Ideally, it should also handle being a part of a reactive form.

**Comment by nektobit** [comment]
It seems to me that I solved all my problems with the autosize, I did this:
1. Install this: https://github.com/TinkoffCreditSystems/angular-contenteditable-accessor
2. Create simple editable div:
```
                  <div
                    [formControl]="form.get('header')"
                    contenteditable
                  ></div>
```
3. Textarea look solved by CSS:
```
div {
    resize: both;
    overflow: hidden;
}
```
4. And last step placeholder - https://codepen.io/flesler/pen/AEIFc

**Comment by evseevdev** [comment]
@gangamweb @RenuDaffodilsw @HrideshDaffodil @josexs @martijnluyckx @kombadzomba @nbunney @MrCroft @nektobit  please, update package version to 2.0.1
