### ISSUE TITLE
Set a minimal amount of rows with autosize

### ISSUE THREAD

**Issue by RaphL** [evseevdev/ngx-textarea-autosize#11]
Hello !

Before the update 2.0 I could specify a minimal amount of row (like : rows="3") with autosize in a textarea. Now it does't seems to work. Is there a way to do that please ?

I thank you in advance !

**Comment by hugodes** [comment]
same issue here

**Comment by hugodes** [comment]
Hi, any news on this ?

**Comment by nektobit** [comment]
same issue :(

**Comment by rluckez** [comment]
As a workaround you can set min-height of textarea, also, you can use your font-size or line-height as a value to multiply by the number of lines you want.
For example:
textarea with font-size = 20px and rows = 3
3 X 20 = 60px
`.my-textarea { 
    min-height: 60px
}`

**Comment by nektobit** [comment]
> As a workaround you can set min-height of textarea, also, you can use your font-size or line-height as a value to multiply by the number of lines you want.
Sometimes it is not very convenient to operate on the height, instead of the number of rows. But I solved the problem anyway in this way: https://github.com/evseevdev/ngx-textarea-autosize/issues/10

**Comment by evseevdev** [comment]
@RaphL @nektobit @hugodes @rluckez please, update package version to 2.0.1
