### ISSUE TITLE
Auto decrease 'textarea' height when in an 'input-group'

### ISSUE THREAD

**Issue by gcfabri** [evseevdev/ngx-textarea-autosize#2]
First of all, thank you for making this module available.

I am using bootstrap 4 in my project and I have this following part of code:

```html
<div class="input-group">
  <textarea class="card-block form-control" wrap="soft" style="border: none; outline: none; resize: none;">Bacon ipsum dolor amet strip steak frankfurter</textarea>
  <span class="input-group-addon">:</span>
  <textarea class="card-block form-control" wrap="soft" style="border: none; outline: none; resize: none;">Bacon ipsum dolor amet strip steak frankfurter corned beef burgdoggen.</textarea>
</div>
```

When added the 'autosize' to both 'textarea' the height is adjusted only for higher values, when the text is deleted the height is not resized to a lower value. Just when the directive is added to one of them.

**Comment by evseevdev** [comment]
Hello, @gcfabri. I couldn't repeat your bug. Can you show me live example with this bug?
