### ISSUE TITLE
ngx-textarea-autosize in Angular5

### ISSUE THREAD

**Issue by cointreau17** [evseevdev/ngx-textarea-autosize#4]
Hi
In Angular4 it works fine, but It is possible use the plugin in Angular5? Server returns this error:

ERROR in ./node_modules/ngx-textarea-autosize/index.ts
Module build failed: Error: /test/project/node_modules/ngx-textarea-autosize/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/test/project/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:656:23)
    at plugin.done.then (/test/project/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
 @ ./src/app/app.module.ts 18:30-62
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

Thanks

**Comment by smasala** [comment]
+1

**Comment by carmencalle** [comment]
Same issue!

**Comment by evseevdev** [comment]
Hi! Thanks for issue. I'll fix it.

**Comment by saiyaff** [comment]
Having the same issue. Any fixes? @evseevdev

**Comment by jerguslejko** [comment]
+1

**Comment by DarekDarecki** [comment]
+1

**Comment by ondrakoupil** [comment]
+1

**Comment by Eraldo** [comment]
+1

**Comment by abel-rodriguez** [comment]
+1

**Comment by abdatta** [comment]
+1

**Comment by jaronwright** [comment]
+1

**Comment by David-Mulder** [comment]
Temporary fix: 
===
add

    "include": [ "node_modules/ngx-textarea-autosize/*.ts", "src/**/*.ts" ],

to `tsconfig.json`

For the author of this repository
===
Explains both why this isn't supported anymore and how to fix it https://ljn.io/posts/publishing-typescript-projects-with-npm/

**Comment by evseevdev** [comment]
Fix it in 2.0 version!  @smasala, @carmencalle, @saiyaff, @jerguslejko, @DarekDarecki, @ondrakoupil, @Eraldo, @abdatta, @jaronwright, @David-Mulder  Please, update to 2.0 version.
